language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

# Install dependencies
install:
 - pip install tornado ptyprocess

# command to run tests
script: 
  - py.test
  - pip install flit
  - flit install --symlink

# Enable new Travis stack, should speed up builds
sudo: false
