language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

# Install dependencies
install: pip install .

# command to run tests
script: nosetests

# Enable new Travis stack, should speed up builds
sudo: false
